### ISSUE TITLE
Bug at Startup

### ISSUE THREAD

**Issue by AndreKoepke** [Eng-Fouad/JTelegramBot#5]
I got this error when I start the bot. When I implement the UpdateHandler myself, I got this error too.

My code:
```
        _bot = new JTelegramBot("HomeSweetHome", _apiKey, new SimpleUpdateHandler());
        _bot.start();
```

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "language_code" (class io.fouad.jtb.core.beans.User), not marked as ignorable (4 known properties: "first_name", "id", "last_name", "username"])
 at [Source: {"ok":true,"result":[{"update_id":BLANKD,
"message":{"message_id":BLANKED,"from":{"id":BLANKED,"first_name":"Andre","username":"BLANKED","language_code":"de-DE"},"chat":{"id":BLANKED,"first_name":"Andre","username":"BLANKED","type":"private"},"date":1501097334,"text":"hi"}}]}
; line: 2, column: 114] (through reference chain: io.fouad.jtb.core.beans.TelegramResult["result"]->Object[][0]->io.fouad.jtb.core.beans.Update["message"]->io.fouad.jtb.core.beans.Message["from"]->io.fouad.jtb.core.beans.User["language_code"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1083)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1389)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1367)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
	at io.fouad.jtb.core.utils.JsonUtils.toJavaObject(JsonUtils.java:51)
	at io.fouad.jtb.core.JTelegramBot.getNewUpdates(JTelegramBot.java:288)
	at io.fouad.jtb.core.JTelegramBot.startPolling(JTelegramBot.java:161)
	at io.fouad.jtb.core.JTelegramBot.start(JTelegramBot.java:121)
	at io.fouad.jtb.core.JTelegramBot.start(JTelegramBot.java:87)
	at com.me.automizer.TelegramSender.<init>(TelegramSender.java:25)
	at com.me.Main.main(Main.java:12)
```

**Comment by pintarj** [comment]
I also get this error.

**Comment by joluj** [comment]
Quick Fix: Add these lines of code in `io.fouad.jtb.core.beans.User`. I didn't commit because the getters and setters are still missing, but at least it won't break.

	/**
	 * Is it a bot (true) oder a real person?
	 */
	@JsonProperty("is_bot")
	private boolean is_bot;

	/**
	 * Users's Language Code
	 */
	@JsonProperty("language_code")
	private String language_code;

Update: **BETTER SOLUTION** See [this answer](https://github.com/Eng-Fouad/JTelegramBot/issues/6#issuecomment-382259388)
